# Generated by Django 4.2.6 on 2023-11-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_block_blocked_by_alter_block_blocked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
